/* Home overview uses the existing records and opens the original forms. */
PAGE_META.home={title:'ภาพรวมงานสมาคม',subtitle:'เอกสาร การเงิน การสนับสนุน และกำหนดการในหน้าเดียว',mobileSubtitle:'สมาคมลับ · งานสมาคม',action:'เพิ่มงานใหม่'};
const Home={filter:'ทั้งหมด',month:new Date().getMonth(),year:new Date().getFullYear(),day:null,rows:[],recent:[]};
const homeText=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const homeIcon=k=>`<i class="ti ti-${{doc:'files',finance:'cash',support:'heart-handshake',calendar:'calendar'}[k]}" aria-hidden="true"></i>`;
const homeAmount=v=>Number(v||0).toLocaleString('th-TH',{maximumFractionDigits:2});
function homeEventRange(r){const start=dateInputValue(r.date_start);return {start,end:dateInputValue(r.date_end)||start};}
function homeEventsInRange(start,end){return calState.records.filter(r=>{const d=homeEventRange(r);return d.start&&d.start<=end&&d.end>=start;}).sort((a,b)=>String(a.date_start).localeCompare(String(b.date_start)));}
function homeTasks(){
 const docs=state.records.filter(r=>r.status==='pend').map(r=>({kind:'doc',type:'เอกสาร',id:r.id,title:r.subject||'หนังสือรับ–ส่ง',sub:[r.docno,r.type==='send'?r.to_org:r.from_org].filter(Boolean).join(' · '),status:'รอดำเนินการ',date:dateInputValue(r.deadline),stamp:r.created_at}));
 const finance=finState.records.filter(r=>['pending','refund','pend'].includes(r.status)).map(r=>({kind:'finance',type:'การเงิน',id:r.id,title:r.title||'รายการการเงิน',sub:[r.requester,'ยอดขอเบิก '+homeAmount(r.amount_request)+' บาท'].filter(Boolean).join(' · '),status:finStatusLabel(r.status),date:'',stamp:r.created_at}));
 const support=Support.records.filter(r=>!['เสร็จแล้ว','ยกเลิก'].includes(r.fulfilment)&&r.decision!=='ไม่อนุมัติ').map(r=>({kind:'support',type:'การสนับสนุน',id:r.id,title:r.title,sub:r.agency,status:r.decision==='รอพิจารณา'?'รอพิจารณา':r.fulfilment||'รอดำเนินการ',date:dateInputValue(r.event_date),stamp:r.created_at}));
 return [...docs,...finance,...support].sort((a,b)=>{if(a.date&&b.date)return a.date.localeCompare(b.date);if(a.date||b.date)return a.date?-1:1;return String(b.stamp||'').localeCompare(String(a.stamp||''));});
}
function homeRecentRecords(){
 return [
 ...state.records.map(r=>({kind:'doc',type:r.type==='send'?'หนังสือส่ง':'หนังสือรับ',id:r.id,title:r.subject||'หนังสือรับ–ส่ง',sub:r.docno,stamp:r.updated_at||r.created_at||r.received_date||r.send_date||r.issue_date})),
 ...finState.records.map(r=>({kind:'finance',type:'การเงิน',id:r.id,title:r.title||'รายการการเงิน',sub:finStatusLabel(r.status),stamp:r.updated_at||r.created_at||r.request_date})),
 ...Support.records.map(r=>({kind:'support',type:'สนับสนุน',id:r.id,title:r.title,sub:r.agency,stamp:r.updated_at||r.created_at})),
 ...calState.records.map(r=>({kind:'calendar',type:'ปฏิทิน',id:r.id,title:r.title,sub:r.location,stamp:r.updated_at||r.created_at}))
 ].filter(r=>r.stamp).sort((a,b)=>(Date.parse(b.stamp)||0)-(Date.parse(a.stamp)||0)).slice(0,5);
}
function renderHome(){
 const page=document.getElementById('page-home');if(!page)return;
 const today=localDateISO(),end=new Date();end.setDate(end.getDate()+6);
 const all=homeTasks(),docs=all.filter(r=>r.kind==='doc'),finance=all.filter(r=>r.kind==='finance'),support=all.filter(r=>r.kind==='support'),events=homeEventsInRange(today,localDateISO(end));
 const cards=[['เอกสารรอดำเนินการ',docs.length,'รายการ','หนังสือรับและหนังสือส่ง','เอกสาร'],['การเงินรอดำเนินการ',finance.length,'รายการ','ยอดขอเบิก '+homeAmount(finState.records.filter(r=>['pending','refund','pend'].includes(r.status)).reduce((s,r)=>s+(Number(r.amount_request)||0),0))+' บาท','การเงิน'],['การสนับสนุนที่ยังไม่เสร็จ',support.length,'กิจกรรม','รอพิจารณาหรือส่งมอบ','การสนับสนุน'],['กิจกรรมใน 7 วันข้างหน้า',events.length,'กิจกรรม','รวมกิจกรรมที่กำลังจัดอยู่','calendar']];
 page.innerHTML=`<section class="hello"><div><h2>วันนี้มีอะไรต้องทำบ้าง</h2><p class="muted">${homeText(new Date().toLocaleDateString('th-TH',{weekday:'long',day:'numeric',month:'long',year:'numeric'}))}</p></div><button class="primary" onclick="homeAddMenu()">＋ เพิ่มงานใหม่</button></section><section class="summary" aria-label="สรุปงานค้าง">${cards.map(([label,n,unit,hint,type])=>`<button data-home-filter="${type}"><label>${label}</label><div class="number">${n}<small>${unit}</small></div><span class="hint">${hint}</span></button>`).join('')}</section><div class="grid"><div><section class="panel"><div class="panel-head"><div><h3>งานที่ต้องดำเนินการ</h3><p class="muted">หยิบงานต่อได้จากตรงนี้</p></div><button class="text-button" onclick="homeAllTasks()">ดูทั้งหมด ↗</button></div><div class="tabs" id="home-tabs" role="group" aria-label="ประเภทงาน"></div><div id="home-tasks"></div><div class="footer-line" id="home-task-count"></div></section><div class="quick">${homeQuickButtons()}</div><section class="panel recent"><div class="panel-head"><h3>รายการล่าสุด</h3><span class="muted">จากทุกส่วนของระบบ</span></div><div class="recent-head"><span>รายการ</span><span>ประเภท</span><span style="text-align:right">วันที่</span></div><div id="home-recent"></div></section></div><section class="panel right" id="home-calendar-panel"><div><div class="panel-head"><h3>ปฏิทินงาน</h3><button class="text-button" onclick="switchPage('calendar')">เปิดปฏิทิน ↗</button></div><div class="calendar-body"><div class="month"><button aria-label="เดือนก่อน" onclick="homeMoveMonth(-1)">‹</button><b id="home-month-name"></b><button aria-label="เดือนถัดไป" onclick="homeMoveMonth(1)">›</button></div><div class="days week"><span>อา</span><span>จ</span><span>อ</span><span>พ</span><span>พฤ</span><span>ศ</span><span>ส</span></div><div class="days" id="home-days"></div></div></div><div class="upcoming"><h3 id="home-event-title">กิจกรรมใน 7 วันข้างหน้า</h3><div id="home-events"></div><button class="text-button" id="home-reset-events" onclick="Home.day=null;homeRenderCalendar();homeRenderEvents()" hidden>กลับไปดูกิจกรรมใกล้ถึง</button></div></section></div><p class="bottom-note">${API.url?'ข้อมูลจากระบบที่ซิงก์ไว้ · กดซิงก์ข้อมูลเพื่อดึงรายการล่าสุด':'ยังไม่ได้เชื่อม Google Sheets · แสดงข้อมูลที่บันทึกในเครื่องนี้'}</p>`;
 page.querySelectorAll('[data-home-filter]').forEach(el=>el.onclick=()=>{if(el.dataset.homeFilter==='calendar'){document.getElementById('home-calendar-panel').scrollIntoView({behavior:'smooth',block:'center'});}else homeFilter(el.dataset.homeFilter);});
 homeRenderTasks();homeRenderRecent();homeRenderCalendar();homeRenderEvents();
}
function homeFilter(type){Home.filter=type;homeRenderTasks();}
function homeRenderTasks(){
 document.getElementById('home-tabs').innerHTML=['ทั้งหมด','เอกสาร','การเงิน','การสนับสนุน'].map(t=>`<button data-home-tab="${t}" class="${Home.filter===t?'active':''}" aria-pressed="${Home.filter===t}">${t}</button>`).join('');
 document.querySelectorAll('[data-home-tab]').forEach(el=>el.onclick=()=>homeFilter(el.dataset.homeTab));
 const list=homeTasks().filter(r=>Home.filter==='ทั้งหมด'||r.type===Home.filter);Home.rows=list.slice(0,6);
 document.getElementById('home-tasks').innerHTML=Home.rows.length?Home.rows.map((r,i)=>`<button class="task" data-home-row="${i}"><span class="icon">${homeIcon(r.kind)}</span><span class="task-copy"><b>${homeText(r.title)}</b><small>${homeText(r.sub)}</small></span><span class="badge ${r.kind==='support'?'purple':''}">${homeText(r.status)}</span><span class="arrow">›</span></button>`).join(''):'<div class="empty">'+(homeTasks().length?'ไม่มีงานค้างในหมวดนี้':'ยังไม่มีงานที่ต้องดำเนินการ<br>เริ่มงานใหม่ได้จากปุ่มด้านล่าง')+'</div>';
 document.querySelectorAll('[data-home-row]').forEach(el=>el.onclick=()=>homeOpenRecord(Home.rows[Number(el.dataset.homeRow)]));document.getElementById('home-task-count').textContent=`แสดง ${Home.rows.length} จาก ${list.length} รายการ`;
}
function homeOpenRecord(r){if(!r)return;switchPage({doc:'list',finance:'finance',support:'support',calendar:'calendar'}[r.kind]);if(r.kind==='doc')openDetail(r.id);if(r.kind==='finance')openFinDetail(r.id);if(r.kind==='support')supportSelect(r.id);if(r.kind==='calendar')openCalDetail(r.id);}
function homeRenderRecent(){Home.recent=homeRecentRecords();document.getElementById('home-recent').innerHTML=Home.recent.length?Home.recent.map((r,i)=>`<button class="recent-row" data-home-recent="${i}"><span><b>${homeText(r.title)}</b><small>${homeText(r.sub)}</small></span><span>${r.type}</span><time>${homeText(formatDate(dateInputValue(r.stamp)))}</time></button>`).join(''):'<div class="empty">ยังไม่มีรายการล่าสุด<br>เมื่อเริ่มบันทึกข้อมูล รายการจะแสดงที่นี่</div>';document.querySelectorAll('[data-home-recent]').forEach(el=>el.onclick=()=>homeOpenRecord(Home.recent[Number(el.dataset.homeRecent)]));}
function homeQuickButtons(){return [['recv','doc','ลงรับเอกสาร'],['send','doc','ส่งหนังสือ'],['finance','finance','เพิ่มเบิกจ่าย'],['calendar','calendar','เพิ่มกิจกรรม'],['support','support','เพิ่มการสนับสนุน']].map(([type,k,t])=>`<button type="button" onclick="homeAdd('${type}')">${homeIcon(k)} ${t}</button>`).join('');}
function homeAddMenu(){let d=document.getElementById('home-add-dialog');if(!d){document.body.insertAdjacentHTML('beforeend',`<dialog id="home-add-dialog" class="home-add-dialog"><div class="home-add-heading"><h2>เพิ่มงานใหม่</h2><button type="button" aria-label="ปิด" onclick="document.getElementById('home-add-dialog').close()">✕</button></div><p>เลือกงานที่ต้องการเริ่ม</p><div class="home-add-options">${homeQuickButtons()}</div></dialog>`);d=document.getElementById('home-add-dialog');}d.showModal();}
function homeAdd(type){document.getElementById('home-add-dialog')?.close();if(['recv','send'].includes(type)){switchPage('list');openForm(type);}if(type==='finance'){switchPage('finance');openFinForm();}if(type==='calendar'){switchPage('calendar');calState.selectedDate=localDateISO();openCalForm();}if(type==='support'){switchPage('support');openSupportForm();}}
function homeAllTasks(){if(Home.filter==='เอกสาร'){state.filter='pend';state.search='';document.getElementById('search-input').value='';document.querySelectorAll('[data-filter]').forEach(el=>el.classList.toggle('active',el.dataset.filter==='pend'));switchPage('list');}else if(Home.filter==='การเงิน')switchPage('finance');else if(Home.filter==='การสนับสนุน')switchPage('support');else{Home.rows=homeTasks();document.getElementById('home-tasks').innerHTML=Home.rows.length?Home.rows.map((r,i)=>`<button class="task" data-home-row="${i}"><span class="icon">${homeIcon(r.kind)}</span><span class="task-copy"><b>${homeText(r.title)}</b><small>${homeText(r.sub)}</small></span><span class="badge">${homeText(r.status)}</span><span class="arrow">›</span></button>`).join(''):'<div class="empty">ไม่มีงานค้าง</div>';document.querySelectorAll('[data-home-row]').forEach(el=>el.onclick=()=>homeOpenRecord(Home.rows[Number(el.dataset.homeRow)]));document.getElementById('home-task-count').textContent=Home.rows.length+' รายการ';}}
function homeDate(d){return localDateISO(new Date(Home.year,Home.month,d));}
function homeMoveMonth(n){const d=new Date(Home.year,Home.month+n,1);Home.year=d.getFullYear();Home.month=d.getMonth();Home.day=null;homeRenderCalendar();homeRenderEvents();}
function homeRenderCalendar(){const label=new Date(Home.year,Home.month,1).toLocaleDateString('th-TH',{month:'long',year:'numeric'});document.getElementById('home-month-name').textContent=label;const first=new Date(Home.year,Home.month,1).getDay(),count=new Date(Home.year,Home.month+1,0).getDate();document.getElementById('home-days').innerHTML='<span></span>'.repeat(first)+Array.from({length:count},(_,i)=>{const d=i+1,date=homeDate(d);return `<button data-home-day="${d}" class="${date===localDateISO()?'today ':''}${homeEventsInRange(date,date).length?'event ':''}${Home.day===d?'selected':''}" aria-label="${d} ${label}">${d}</button>`}).join('');document.querySelectorAll('[data-home-day]').forEach(el=>el.onclick=()=>{Home.day=Number(el.dataset.homeDay);homeRenderCalendar();homeRenderEvents();});}
function homeRenderEvents(){const end=new Date();end.setDate(end.getDate()+6);const date=Home.day?homeDate(Home.day):localDateISO();const list=homeEventsInRange(date,Home.day?date:localDateISO(end));document.getElementById('home-event-title').textContent=Home.day?new Date(Home.year,Home.month,Home.day).toLocaleDateString('th-TH',{day:'numeric',month:'long',year:'numeric'}):'กิจกรรมใน 7 วันข้างหน้า';document.getElementById('home-reset-events').hidden=!Home.day;document.getElementById('home-events').innerHTML=list.length?list.map((r,i)=>{const d=new Date(dateInputValue(r.date_start)+'T12:00:00');return `<button class="event-row" data-home-event="${i}"><span class="date">${d.getDate()}<small>${homeText(d.toLocaleDateString('th-TH',{month:'short'}))}</small></span><span><b>${homeText(r.title)}</b><small>${homeText(r.time_start?(r.time_start+(r.time_end?'–'+r.time_end:''))+' น.':'ทั้งวัน')}<br>${homeText(r.location||'ยังไม่ระบุสถานที่')}</small>${r.type?'<br><span class="badge purple">'+homeText(r.type)+'</span>':''}</span></button>`;}).join(''):'<p class="empty">'+(Home.day?'ไม่มีกิจกรรมในวันนี้':'ไม่มีกิจกรรมใน 7 วันข้างหน้า')+'</p>';document.querySelectorAll('[data-home-event]').forEach(el=>el.onclick=()=>homeOpenRecord({kind:'calendar',id:list[Number(el.dataset.homeEvent)].id}));}
document.addEventListener('DOMContentLoaded',()=>{if(state.page==='home')renderHome();});
